task: cont_state_llm_num_optim_semantics
num_episodes: 400
gym_env_name: InvertedDoublePendulum-v5
render_mode: null
logdir: logs/IDP_summarise_propsP_best_10_recent_10
dim_actions: 1
dim_states: 9
max_traj_count: 10
max_traj_length: 1000
max_best_length: 10
template_dir: agent/policy/templates
llm_si_template_name: num_optim_semantic.j2
llm_output_conversion_template_name: num_optim_semantic.j2
llm_model_name: gpt-oss:120b
num_evaluation_episodes: 20
warmup_episodes: 20
warmup_dir: null
bias: true
optimum: 10000
search_step_size: 0.1
env_desc_file: env_descriptions/inverteddoublependulum.j2
