task: cont_state_llm_num_reward
num_episodes: 400
gym_env_name: InvertedPendulum-v5
render_mode: null
logdir: reward-logs/memory-simulated/invertedpendulum
dim_actions: 1
dim_states: 4
max_traj_count: 1000
max_traj_length: 1000
max_best_length: 0
template_dir: agent/policy/templates
summary_template: num_optim_stats.j2
llm_si_template_name: num_optim_reward.j2
llm_output_conversion_template_name: num_optim_reward.j2
llm_model_name: gpt-oss:120b
num_evaluation_episodes: 20
warmup_episodes: 20
warmup_dir: null
bias: true
optimum: 1000
search_step_size: 1.0
env_desc_file: env_descriptions/invertedpendulum.j2
summary_desc_file: summary_descriptions/invertedpendulum_summary.j2
summary: false
memory_strategy: default
dataset_file: ip-simulated-params.txt
reward_range: (0, 1000]
run_nn_train: false