task: cont_state_llm_num_optim_semantics
num_episodes: 400
gym_env_name: MountainCar-v0
render_mode: null
logdir: logs/mountaincar_propsp_baseline
dim_actions: 3
dim_states: 2
max_traj_count: 20
max_traj_length: 200
max_best_length: 0
template_dir: agent/policy/templates
summary_template: num_optim_stats.j2
llm_si_template_name: num_optim_semantic.j2
llm_output_conversion_template_name: num_optim_semantic.j2
llm_model_name: gpt-oss:120b
num_evaluation_episodes: 20
warmup_episodes: 20
warmup_dir: null
bias: true
optimum: -120
search_step_size: 1.0
env_desc_file: env_descriptions/mountaincar.j2
summary_desc_file: summary_descriptions/mountaincardiscrete_summary.j2
summary: true
memory_strategy: default